name: 'api-src : test'

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    paths:
      - 'api/src/**'
  push:
    branches: ['main']
    paths:
      - 'api/src/**'

jobs:
  test-api-src:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .makefiles
            Makefile
            config.json
            api/src/
            api/Makefile
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: api/src/package-lock.json
          node-version-file: api/src/package.json
      - name: Init dependencies
        run: make api-init
      - name: Run tests
        run: make api-test
