name: ': deploy'
run-name: Deploy to ${{ inputs.env || 'stg' }}

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
    inputs:
      env:
        required: true
        type: choice
        default: stg
        options:
          - stg
          - prd
  push:
    branches:
      - main
    paths:
      - 'api/**'
      - 'website/**'

concurrency:
  group: ${{ inputs.env || 'stg' }}
  cancel-in-progress: true

jobs:
  gitversion:
    name: Init deploy-${{ inputs.env || 'stg' }}
    uses: ./.github/workflows/gitversion.yml
  package-build:
    name: Build ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/package-build.yml
    needs: gitversion
    with:
      env: ${{ inputs.env || 'stg' }}
      version: ${{ needs.gitversion.outputs.version }}
  package-deploy:
    name: Deploy ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/package-deploy.yml
    needs:
      - package-build
      - gitversion
    with:
      env: ${{ inputs.env || 'stg' }}
  deployment-test:
    name: Test ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/deployment-test.yml
    needs:
      - package-deploy
      - gitversion
    with:
      env: ${{ inputs.env || 'stg' }}
      version: ${{ needs.gitversion.outputs.version }}
