name: 'deployment : test'

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      version:
        type: string

jobs:
  run-apitest:
    name: apitest-${{ inputs.env }}
    uses: ./.github/workflows/apitest-run.yml
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
  run-e2etest:
    name: e2etest-${{ inputs.env }}
    uses: ./.github/workflows/e2etest-run.yml
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
