name: 'deployment : test'

on:
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      version:
        type: string

jobs:
  e2etest-run:
    name: webapp
    uses: ./.github/workflows/e2etest-run.yml
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
