name: '__ gitversion'

on:
  workflow_call:
    outputs:
      version:
        value: v${{ jobs.gitversion.outputs.version }}

jobs:
  gitversion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@2.0.0
        with:
          versionSpec: '5.x'
      - name: Execute GitVersion
        id: gitversion
        uses: gittools/actions/gitversion/execute@2.0.0
        with:
          useConfigFile: true
