
name: 'package : build'

permissions:
  id-token: write
  contents: read

on:
  workflow_call:
    inputs:
      env:
        description: Environment to deploy to
        type: string
        required: true
      version:
        description: Version to build
        type: string
        required: true

jobs:
  build-api:
    name: api
    uses: ./.github/workflows/api-build.yml
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
  build-website-fe:
    name: website-fe
    uses: ./.github/workflows/website-fe-build.yml
    with:
      env: ${{ inputs.env }}
      version: ${{ inputs.version }}
  build-website-infra:
    name: website-infra
    uses: ./.github/workflows/website-infra-build.yml
    with:
      env: ${{ inputs.env }}
  package:
    name: package-${{ inputs.env }}
    runs-on: ubuntu-latest
    needs:
      - build-api
      - build-website-infra
      - build-website-fe
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            ./.makefiles
            ./Makefile
            ./config.json
      - name: Download website-fe deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: website-fe
          path: website/fe
      - name: Download website-infra deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: website-infra
          path: website/infra
      - name: Download api deployment artifact
        uses: actions/download-artifact@v4
        with:
          name: api
          path: api
      - name: Create deployment package
        id: source
        run: zip -r package.zip .makefiles *
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          if-no-files-found: error
          path: package.zip
