name: ': release'

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ['release']

jobs:
  gitversion:
    name: Init release
    uses: ./.github/workflows/gitversion.yml
  package-build:
    name: Build ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/package-build.yml
    needs: gitversion
    with:
      env: prd
      version: ${{ needs.gitversion.outputs.version }}
  deploy-prd:
    name: Deploy ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/package-deploy.yml
    needs:
      - package-build
      - gitversion
    with:
      env: prd
  deployment-test:
    name: Test ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/deployment-test.yml
    needs:
      - deploy-prd
      - gitversion
    with:
      env: prd
      version: ${{ needs.gitversion.outputs.version }}
