name: ': release'

permissions:
  id-token: write
  contents: read

on:
  workflow_dispatch:
  push:
    branches: ['release']

jobs:
  gitversion:
    name: Init release
    uses: ./.github/workflows/gitversion.yml
  package-build:
    name: Build ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/package-build.yml
    needs: gitversion
    with:
      env: prd
      version: ${{ needs.gitversion.outputs.version }}
  release:
    name: Release ${{ needs.gitversion.outputs.version }}
    runs-on: ubuntu-latest
    needs:
      - gitversion
      - package-build
    permissions:
      contents: write
    outputs:
      version: ${{ needs.gitversion.outputs.version }}
    steps:
      - name: Download deployment package
        uses: actions/download-artifact@v4
        with:
          name: package
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ needs.gitversion.outputs.version }}
          artifacts: package.zip
          makeLatest: true
  deploy-prd:
    name: Deploy ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/package-deploy.yml
    needs:
      - release
      - gitversion
    with:
      env: prd
  deployment-test:
    name: Test ${{ needs.gitversion.outputs.version }}
    uses: ./.github/workflows/deployment-test.yml
    needs:
      - deploy-prd
      - gitversion
    with:
      env: prd
      version: ${{ needs.gitversion.outputs.version }}
