name: 'website-fe : build'

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        required: true
        default: stg
        type: choice
        options:
          - stg
          - prd
      version:
        description: Version
        type: string
  workflow_call:
    inputs:
      env:
        required: true
        type: string
      version:
        type: string
        required: true
  pull_request:
    branches: ['main']
    paths:
      - 'website/fe/**'

jobs:
  build-website-fe:
    name: website-fe-${{ inputs.env || 'stg' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .makefiles
            config.json
            Makefile
            website/fe
            website/Makefile
      - uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: website/fe/package-lock.json
          node-version-file: website/fe/package.json
      - name: Init dependencies
        run: make website-fe-init-test
      - name: Build frontend
        run: make website-fe-build ENV=${{ inputs.env || 'stg' }} VERSION=${{ inputs.version || '*' }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-fe
          path: |
            website/fe/dist
            website/fe/Makefile
