name: 'website-infra : test'

on:
  workflow_dispatch:
  pull_request:
    branches: ['main']
    paths:
      - 'website/infra/**'
  push:
    branches: ['main']
    paths:
      - 'website/infra/**'

env:
  SAM_CLI_TELEMETRY: 0

jobs:
  test-website-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            .makefiles
            config.json
            Makefile
            website/infra
            website/Makefile
      - name: Run website infrastructure test
        run: make website-infra-test
